# Docker Compose configuration for Todo App
# Run with: docker compose up -d
# Stop with: docker compose down
# Remove volumes: docker compose down -v

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=todoapp
      - DB_SSLMODE=disable
      - PORT=8080
      - GIN_MODE=debug
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - todo-network

volumes:
  postgres_data:
    driver: local

networks:
  todo-network:
    driver: bridge 